@extends('layouts.index')

@section('content')
    @include('sections.last-news')
    @include('sections.special-events')
    @include('sections.best-cources')
    @include('sections.features')
    @include('sections.partners')
    @include('sections.teacher-thoughts')
    @include('sections.numbers')
    @livewire('courses-block-component')
    @include('sections.news')
    @include('sections.events')
    @include('sections.cources-modal')
@endsection